version: '3.8'

services:
  nextjs-app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - NODE_ENV=development
      - API_URL=http://host.docker.internal:8080/api 
    extra_hosts:
      - "host.docker.internal:host-gateway" 
    network_mode: bridge